- resources:
    label: Server Health
    cpu: true
    memory: true
    disk: /
    uptime: true

- search:
    provider: bing
    target: _blank
  
- datetime:
    text_size: xl
    format:
        timeStyle: short
        hourCycle: h23
